### ISSUE TITLE
Broken link on 'Setting Up Rancher With Digital Ocean' post to 'Creating a Linux Virtual Machine Server' post

### ISSUE THREAD

**Issue by TurningOfTables** [futurepixels/futurepixels.co.uk#28]
[This post for Setting Up Rancher With Digital Ocean](https://github.com/futurepixels/futurepixels.co.uk/blob/master/content/posts/2018-08-02-setting-up-rancher-with-digital-ocean.md) has a broken link to the 'Creating a Linux Virtual Machine Server' post.

URL currently goes to /posts/creating-a-linux-virtual-machine-server-with-the-hp-microserver-gen-8-serve:rboard.org/k

Think it should be /posts/creating-a-linux-virtual-machine-server-with-the-hp-microserver-gen-8-server

**Comment by NigelGreenway** [comment]
This is also fixed, can you concur please @TurningOfTables :P
